// lorem-angular-fs/src/app/lorem/lorem.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lorem',
  templateUrl: './lorem.component.html',
  styleUrls: ['./lorem.component.scss']
})
export class LoremComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div id="lorem" class="grid-container">

    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-4">

            <h4>Lorem Ipsum</h4>
            <h5>1.10.32 de Finibus Bonorum et Malorum</h5>
            <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab
                illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut
                odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
                voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum
                quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam
                eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam
                corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
                Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse
                quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo
                voluptas nulla pariatur?
            </p>

        </div>
        <div class="cell medium-4">

            <h5>1.10.33 de Finibus Bonorum et Malorum</h5>
            <p>
                At vero eos et accusamus et iusto odio dignissimos ducimus qui
                blanditiis praesentium voluptatum deleniti atque corrupti quos dolores
                et quas molestias excepturi sint occaecati cupiditate non provident,
                similique sunt in culpa qui officia deserunt mollitia animi, id est
                laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita
                distinctio. Nam libero tempore, cum soluta nobis est eligendi optio
                cumque nihil impedit quo minus id quod maxime placeat facere possimus,
                omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem
                quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet
                ut et voluptates repudiandae sint et molestiae non recusandae. Itaque
                earum rerum hic tenetur a sapiente delectus, ut aut reiciendis
                voluptatibus maiores alias consequatur aut perferendis doloribus
                asperiores repellat.
            </p>
        </div>

    </div>
</div>

// lorem-vue-ts/src/Lorem.vue
<template>
    <div id="lorem" class="grid-container">

        <div class="grid-x grid-margin-x align-center">
            <div class="cell medium-4">

                <h4>Lorem Ipsum</h4>
                <h5>1.10.32 de Finibus Bonorum et Malorum</h5>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab
                    illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut
                    odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
                    voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum
                    quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam
                    eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                    voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam
                    corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
                    Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse
                    quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo
                    voluptas nulla pariatur?
                </p>

            </div>
            <div class="cell medium-4">

                <h5>1.10.33 de Finibus Bonorum et Malorum</h5>
                <p>
                    At vero eos et accusamus et iusto odio dignissimos ducimus qui
                    blanditiis praesentium voluptatum deleniti atque corrupti quos dolores
                    et quas molestias excepturi sint occaecati cupiditate non provident,
                    similique sunt in culpa qui officia deserunt mollitia animi, id est
                    laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita
                    distinctio. Nam libero tempore, cum soluta nobis est eligendi optio
                    cumque nihil impedit quo minus id quod maxime placeat facere possimus,
                    omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem
                    quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet
                    ut et voluptates repudiandae sint et molestiae non recusandae. Itaque
                    earum rerum hic tenetur a sapiente delectus, ut aut reiciendis
                    voluptatibus maiores alias consequatur aut perferendis doloribus
                    asperiores repellat.
                </p>
            </div>

        </div>
    </div>

</template>

<script lang="ts">

import { mapState, mapGetters, mapActions } from 'vuex'
import foundation from './foundation'

import { Vue, Component, Prop } from "vue-property-decorator"

@Component
export default class Lorem extends Vue {

    mounted() {
        foundation('#lorem')
        console.log('Lorem mounted')
    }
}
</script>
